# Custom config for scss-lint
# Find an example of all options here: https://github.com/causes/scss-lint/blob/master/config/default.yml

linters:
  Indentation:
    enabled: false

  Comment:
    enabled: false

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  NameFormat:
    enabled: false
    convention: BEM
